---
title: C6312 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: 2f33d2a6e7e87f14859614fa25e1bd846764b944
ms.sourcegitcommit: 6cfffa72af599a9d667249caaaa411bb28ea69fd
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 09/02/2020
ms.locfileid: "77273921"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

경고 C6312: 가능한 무한 루프: try-except의 예외 필터 식에서 상수 EXCEPTION_CONTINUE_EXECUTION 사용  
  
 이 경고는 `EXCEPTION_CONTINUE_EXECUTION` 구조적 예외 처리기의 필터 식에서 상수 (또는-1로 계산 되는 다른 상수)의 사용을 나타냅니다. 상수 값을 사용 하면 `EXCEPTION_CONTINUE_EXECUTION` 무한 루프가 발생할 수 있습니다. 예를 들어, 하드웨어에서 예외가 발생 한 경우 예외를 발생 시킨 명령이 다시 시작 됩니다. 예외를 발생 시킨 주소가 여전히 잘못 된 경우 다른 예외가 발생 하 여 동일한 방식으로 처리 됩니다. 이로 인해 무한 루프가 발생 합니다.  
  
 에 대 한 명시적 호출은 `RaiseException` 무한 루프를 직접 발생 시 키 지 않지만 보호 된 블록에서 코드를 계속 실행 합니다. 이는 예기치 않은 일 수 있으며, `RaiseException` 잘못 된 포인터를 역참조 하지 않도록를 사용 하는 경우 무한 루프가 발생할 수 있습니다.  
  
 일반적으로는 `EXCEPTION_CONTINUE_EXECUTION` 필터 식에서 호출 되는 함수에 의해서만 반환 되어야 합니다 .이 함수는 예외를 발생 시킨 포인터 또는 기본 메모리를 수정할 수 있습니다.  
  
## <a name="example"></a>예  
 다음 코드에서는이 경고를 생성 합니다.  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 이 경고를 해결 하려면 다음 코드를 사용 합니다.  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```
